### ISSUE TITLE
Project installs a `scripts` package

### ISSUE THREAD

**Issue by jaraco** [unfor19/githubsecrets#17]
This project installs a `scripts` package. That generic namespace is not suitably isolated from other packages. I recommend the project should install a `githubsecrets` package instead.

Let me know if I can help.

**Comment by unfor19** [comment]
Hi @jaraco , thanks for pointing it out! I've just created a PR that should solve this. Once all tests are complete I'll merge it, and then you can take a look at the `master` branch

**Comment by unfor19** [comment]
Seems like the new version has issues, working on it

**Comment by unfor19** [comment]
@jaraco - it seems like it works when I run it from Docker, but I think something is corrupted in my local machine.
Can you please confirm that version `1.0.6` works on your machine, after using `pip -U` ?

**Comment by jaraco** [comment]
It's not working for me yet.

```
~ $ pip-run githubsecrets -- -c "import githubsecrets" && echo done
Collecting githubsecrets
  Downloading githubsecrets-1.0.6-py3-none-any.whl (5.3 kB)
Collecting requests>=2.23.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting Click>=7.1.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting PyNaCl>=1.3.0
  Using cached PyNaCl-1.4.0-cp35-abi3-macosx_10_10_x86_64.whl (380 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting keyring>=21.2.0
  Using cached keyring-21.4.0-py3-none-any.whl (31 kB)
Collecting cryptography>=2.9
  Using cached cryptography-3.1.1-cp35-abi3-macosx_10_10_x86_64.whl (1.8 MB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting cffi>=1.4.1
  Using cached cffi-1.14.3-2-cp39-cp39-macosx_10_9_x86_64.whl (176 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Installing collected packages: pycparser, urllib3, six, idna, chardet, cffi, certifi, requests, PyNaCl, keyring, cryptography, Click, githubsecrets
Successfully installed Click-7.1.2 PyNaCl-1.4.0 certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 cryptography-3.1.1 githubsecrets-1.0.6 idna-2.10 keyring-21.4.0 pycparser-2.20 requests-2.24.0 six-1.15.0 urllib3-1.25.10
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'githubsecrets'
```

**Comment by jaraco** [comment]
Same at master:

```
~ $ pip-run --use-pep517 git+https://github.com/unfor19/githubsecrets -- -c "import githubsecrets" && echo done
Collecting git+https://github.com/unfor19/githubsecrets
  Cloning https://github.com/unfor19/githubsecrets to /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-1z6akgyt
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting PyNaCl>=1.3.0
  Using cached PyNaCl-1.4.0-cp35-abi3-macosx_10_10_x86_64.whl (380 kB)
Collecting requests>=2.23.0
  Using cached requests-2.24.0-py2.py3-none-any.whl (61 kB)
Collecting Click>=7.1.1
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting keyring>=21.2.0
  Using cached keyring-21.4.0-py3-none-any.whl (31 kB)
Collecting cryptography>=2.9
  Using cached cryptography-3.1.1-cp35-abi3-macosx_10_10_x86_64.whl (1.8 MB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.10-py2.py3-none-any.whl (127 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Collecting cffi>=1.4.1
  Using cached cffi-1.14.3-2-cp39-cp39-macosx_10_9_x86_64.whl (176 kB)
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: githubsecrets
  Building wheel for githubsecrets (PEP 517) ... done
  Created wheel for githubsecrets: filename=githubsecrets-0.0.1-py3-none-any.whl size=5255 sha256=e61ce77cd39fa94e39bc72a7f9ee33189403cf286b1d544cffa7f8404a4028fa
  Stored in directory: /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-ephem-wheel-cache-zwh3gk2s/wheels/dc/54/7f/ecd03d0cb374eb7c4a054fc092e87e500734b70e38bf59f55b
Successfully built githubsecrets
Installing collected packages: pycparser, urllib3, six, idna, chardet, cffi, certifi, requests, PyNaCl, keyring, cryptography, Click, githubsecrets
Successfully installed Click-7.1.2 PyNaCl-1.4.0 certifi-2020.6.20 cffi-1.14.3 chardet-3.0.4 cryptography-3.1.1 githubsecrets-0.0.1 idna-2.10 keyring-21.4.0 pycparser-2.20 requests-2.24.0 six-1.15.0 urllib3-1.25.10
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'githubsecrets'
```

**Comment by jaraco** [comment]
Interesting how installation at master has v0.0.1.

**Comment by jaraco** [comment]
I think the issue is that `githubsecrets/__init__.py` is missing.

**Comment by jaraco** [comment]
You might be asking yourself, "but why does it work in Docker?" It's probably because you're using an editable install or otherwise have the `githubsecrets` folder on the python path, and on Python 3, that creates a namespace package, but when packaging, Setuptools won't find that package in `find_packages` without some additional handling. But unless you really want `githubsecrets` to be a namespace package where other distributions can add modules and other sub-packages, then you probably just want to bring the `__init__.py` back.

**Comment by unfor19** [comment]
@jaraco - Superb, I've added `__init__.py` to the `githubsecrets` package, seems like all imports are working properly, releasing version v1.0.7 in a few mins

**Comment by unfor19** [comment]
@jaraco - Updated version v1.0.7 - everything seems to be working.

The package name is `githubsecrets` and I also added `__main__.py` to it, so you can run it with

```
python -m githubsecrets
```

**Comment by jaraco** [comment]
Confirmed. Works great. Thanks!
